### ISSUE TITLE
debian

### ISSUE THREAD

**Issue by ehabheikal** [ugoviti/synbak#1]
I am trying to run synbak with a debian derived distro, when i run the synbak command with rsync it just hangs for hours and does not produce output. Is there a way to debug and see where it is hanging?

**Comment by ehabheikal** [comment]
I had to change the following in functions.sh
#echo "We are using netcat!!!"
           netcat -z -t 2 "$1" "$2" </dev/null >/dev/null 2>&1

I added -z t 2 for it to work

**Comment by ugoviti** [comment]
changed upstream. Thank you
